/*
 * 7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량 순으로 상위 3개
*/
# SELECT j.FLAVOR, (j.TOTAL_ORDER + fh.TOTAL_ORDER) as TOTAL_ORDER
# SELECT *
# FROM JULY as j LEFT JOIN  FIRST_HALF as fh ON j.FLAVOR = fh.FLAVOR
# ORDER BY TOTAL_ORDER DESC
# LIMIT 3
SELECT j.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) as j LEFT JOIN
(SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF
GROUP BY FLAVOR) as fh ON j.FLAVOR = fh.FLAVOR
ORDER BY (j.TOTAL_ORDER + fh.TOTAL_ORDER) DESC
LIMIT 3