/*
 
    - 2022년 10월 16일
    - 반납 날짜가 2022년 10월 16일인 경우에도 '대여중'
    - 자동차 ID 내림차
*/
# SELECT CAR_ID, START_DATE+
# # FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# FROM 
# GROUP BY CAR_ID
# SELECT CAR_ID,
#     (CASE WHEN CAR_ID IN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE '2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-d') AND DATE_FORMAT(END_DATE, '%Y-m-d'))
#         THEN '대여중'
#         ELSE '대여 가능' 
#         END) AS 'AVAILABILITY'
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC 

SELECT CAR_ID,
(CASE WHEN CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d'))
THEN '대여중'
ELSE '대여 가능'
END) AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC